Algoritmo "crescente"
//
//

// Data atual  : 01/03/2026
Var

   x, y : inteiro

Inicio

   escreval("Digite dois numeros: ")
   leia(x)
   leia(y)

   enquanto x <> y faca

      se x > y entao
         escreval("DECRESCENTE!")
      senao
         escreval("CRESCENTE!")
      fimse

      escreval("Digite outro número: ")
      leia(x)
      leia(y)

   fimenquanto






Fimalgoritmo